# Generated by Django 3.2.13 on 2024-01-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payplan',
            name='pay_plan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
